"""AUTO-GENERATED by mine_mmp_rules.py — do not edit by hand.

Mined 131 single-cut MMP transformation rules from authentic@intelligent_pharma_50k_v2.pt,
ranked by matched-pair support. Format matches MMP_TRANSFORMATIONS in
mmp_transformations.py:
    (name, difficulty, category, reactant, product, citation)
"""

from typing import List, Tuple

MMP_TRANSFORMATIONS: List[Tuple[str, str, str, str, str, str]] = [
    ('mmp0000_RC_to_RCC', 'subtle', 'homologation',
     '[*:1]C',
     '[*:1]CC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=31 pairs, Δheavy=1
    ('mmp0001_RCFFF_to_RCl', 'moderate', 'halogen-walk',
     '[*:1]C(F)(F)F',
     '[*:1]Cl',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=17 pairs, Δheavy=-3
    ('mmp0002_Rc1cccClcc1_to_Rc1ccccc1', 'subtle', 'halogen-walk',
     '[*:1]c1ccc(Cl)cc1',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=14 pairs, Δheavy=-1
    ('mmp0003_RO_to_ROPeqOOO', 'obvious', 'bioisostere',
     '[*:1]O',
     '[*:1]OP(=O)(O)O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=13 pairs, Δheavy=4
    ('mmp0004_RC1CCCCC1_to_Rc1ccccc1', 'subtle', 'scaffold-hop',
     '[*:1]C1CCCCC1',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=13 pairs, Δheavy=0
    ('mmp0005_Rc1ccccc1_to_Rc1cccs1', 'subtle', 'bioisostere',
     '[*:1]c1ccccc1',
     '[*:1]c1cccs1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=12 pairs, Δheavy=-1
    ('mmp0006_RC1CCCC1_to_RC1CCCCC1', 'subtle', 'homologation',
     '[*:1]C1CCCC1',
     '[*:1]C1CCCCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=11 pairs, Δheavy=1
    ('mmp0007_RC_to_RCl', 'subtle', 'halogen-walk',
     '[*:1]C',
     '[*:1]Cl',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=11 pairs, Δheavy=0
    ('mmp0008_RC_to_RCC1CC1', 'moderate', 'scaffold-hop',
     '[*:1]C',
     '[*:1]CC1CC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=11 pairs, Δheavy=3
    ('mmp0009_RO_to_ROC', 'subtle', 'homologation',
     '[*:1]O',
     '[*:1]OC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=11 pairs, Δheavy=1
    ('mmp0010_RC_to_RCCCC', 'moderate', 'homologation',
     '[*:1]C',
     '[*:1]CCCC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=10 pairs, Δheavy=3
    ('mmp0011_Rc1cccBrcc1_to_Rc1cccClcc1', 'subtle', 'halogen-walk',
     '[*:1]c1ccc(Br)cc1',
     '[*:1]c1ccc(Cl)cc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=9 pairs, Δheavy=0
    ('mmp0012_Rc1ccccc1_to_Rc1ccccc1Cl', 'subtle', 'halogen-walk',
     '[*:1]c1ccccc1',
     '[*:1]c1ccccc1Cl',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=9 pairs, Δheavy=1
    ('mmp0013_RNCC_to_RNC', 'subtle', 'homologation',
     '[*:1]N(C)C',
     '[*:1]NC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=9 pairs, Δheavy=-1
    ('mmp0014_RCC_to_RCCO', 'subtle', 'bioisostere',
     '[*:1]CC',
     '[*:1]CCO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=9 pairs, Δheavy=1
    ('mmp0015_RC_to_RCCO', 'moderate', 'bioisostere',
     '[*:1]C',
     '[*:1]CCO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=9 pairs, Δheavy=2
    ('mmp0016_RBr_to_RCl', 'subtle', 'halogen-walk',
     '[*:1]Br',
     '[*:1]Cl',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=9 pairs, Δheavy=0
    ('mmp0017_RC1CCCC1_to_Rc1ccccc1', 'subtle', 'scaffold-hop',
     '[*:1]C1CCCC1',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=8 pairs, Δheavy=1
    ('mmp0018_RO_to_ROCCeqO', 'moderate', 'homologation',
     '[*:1]O',
     '[*:1]OC(C)=O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=8 pairs, Δheavy=3
    ('mmp0019_RC_to_RCCeqC', 'moderate', 'homologation',
     '[*:1]C',
     '[*:1]CC=C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=8 pairs, Δheavy=2
    ('mmp0020_RNCCCC_to_RNCCCCO', 'subtle', 'bioisostere',
     '[*:1]N(CC)CC',
     '[*:1]N(CC)CCO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=8 pairs, Δheavy=1
    ('mmp0021_RNCC_to_RN1CCNCCC1', 'obvious', 'scaffold-hop',
     '[*:1]N(C)C',
     '[*:1]N1CCN(C)CC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=8 pairs, Δheavy=4
    ('mmp0022_RCl_to_RF', 'subtle', 'halogen-walk',
     '[*:1]Cl',
     '[*:1]F',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=8 pairs, Δheavy=0
    ('mmp0023_Rc1cccOcc1_to_Rc1ccccc1', 'subtle', 'bioisostere',
     '[*:1]c1ccc(O)cc1',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=7 pairs, Δheavy=-1
    ('mmp0024_Rc1cccBrcc1_to_Rc1ccccc1', 'subtle', 'halogen-walk',
     '[*:1]c1ccc(Br)cc1',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=7 pairs, Δheavy=-1
    ('mmp0025_RN1CCCC1_to_RN1CCCCC1', 'subtle', 'homologation',
     '[*:1]N1CCCC1',
     '[*:1]N1CCCCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=7 pairs, Δheavy=1
    ('mmp0026_RC_to_RCCOCCO', 'obvious', 'bioisostere',
     '[*:1]C',
     '[*:1]CCOCCO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=7 pairs, Δheavy=5
    ('mmp0027_RCc1ccccc1_to_RCc1cccs1', 'subtle', 'bioisostere',
     '[*:1]Cc1ccccc1',
     '[*:1]Cc1cccs1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=-1
    ('mmp0028_RC_to_RCCC', 'moderate', 'homologation',
     '[*:1]C',
     '[*:1]CCC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=2
    ('mmp0029_Rc1cccClcc1_to_Rc1cccClcc1Cl', 'subtle', 'halogen-walk',
     '[*:1]c1ccc(Cl)cc1',
     '[*:1]c1ccc(Cl)cc1Cl',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=1
    ('mmp0030_RC1CCCC1_to_Rc1cccs1', 'subtle', 'scaffold-hop',
     '[*:1]C1CCCC1',
     '[*:1]c1cccs1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=0
    ('mmp0031_RC1CCCCC1_to_Rc1cccs1', 'subtle', 'scaffold-hop',
     '[*:1]C1CCCCC1',
     '[*:1]c1cccs1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=-1
    ('mmp0032_Rc1ccccc1_to_Rc1ccccn1', 'subtle', 'bioisostere',
     '[*:1]c1ccccc1',
     '[*:1]c1ccccn1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=0
    ('mmp0033_RCCNCC_to_ROCCNCC', 'subtle', 'bioisostere',
     '[*:1]CCN(C)C',
     '[*:1]OCCN(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=1
    ('mmp0034_RCl_to_RO', 'subtle', 'bioisostere',
     '[*:1]Cl',
     '[*:1]O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=0
    ('mmp0035_RCCCNCC_to_RCCCNC', 'subtle', 'homologation',
     '[*:1]CCCN(C)C',
     '[*:1]CCCNC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=-1
    ('mmp0036_RCCCCNCC_to_RCCCNCC', 'subtle', 'homologation',
     '[*:1]CC(C)CN(C)C',
     '[*:1]CCCN(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=-1
    ('mmp0037_RC_to_RCCC', 'moderate', 'homologation',
     '[*:1]C',
     '[*:1]C(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=2
    ('mmp0038_RCCCl_to_RCCO', 'subtle', 'bioisostere',
     '[*:1]CCCl',
     '[*:1]CCO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=0
    ('mmp0039_RCCO_to_RCCOPeqOOO', 'obvious', 'bioisostere',
     '[*:1]CCO',
     '[*:1]CCOP(=O)(O)O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=6 pairs, Δheavy=4
    ('mmp0040_Rc1cccOCcc1_to_Rc1ccccc1', 'moderate', 'bioisostere',
     '[*:1]c1ccc(OC)cc1',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=5 pairs, Δheavy=-2
    ('mmp0041_RCCN1CCCC1_to_RCCN1CCCCC1', 'subtle', 'homologation',
     '[*:1]CCN1CCCC1',
     '[*:1]CCN1CCCCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=5 pairs, Δheavy=1
    ('mmp0042_ROCCeqOO_to_ROCCO', 'subtle', 'homologation',
     '[*:1]OCC(=O)O',
     '[*:1]OCCO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=5 pairs, Δheavy=-1
    ('mmp0043_RC1CCNCCC1_to_RCCNCC', 'moderate', 'scaffold-hop',
     '[*:1]C1CCN(C)CC1',
     '[*:1]CCN(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=5 pairs, Δheavy=-2
    ('mmp0044_RCCOCCeqOO_to_RCCOCCO', 'subtle', 'homologation',
     '[*:1]CCOCC(=O)O',
     '[*:1]CCOCCO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=5 pairs, Δheavy=-1
    ('mmp0045_RCCeqOO_to_RCCO', 'subtle', 'homologation',
     '[*:1]CC(=O)O',
     '[*:1]CCO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=5 pairs, Δheavy=-1
    ('mmp0046_RCl_to_ROC', 'subtle', 'bioisostere',
     '[*:1]Cl',
     '[*:1]OC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=5 pairs, Δheavy=1
    ('mmp0047_RCCO_to_RCC', 'subtle', 'bioisostere',
     '[*:1]C(C)O',
     '[*:1]CC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=5 pairs, Δheavy=-1
    ('mmp0048_RCtriCCCCC_to_Rc1ccccc1', 'subtle', 'scaffold-hop',
     '[*:1]C#CC(C)(C)C',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=0
    ('mmp0049_RC1CCCO1_to_Rc1ccco1', 'subtle', 'scaffold-hop',
     '[*:1]C1CCCO1',
     '[*:1]c1ccco1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=0
    ('mmp0050_RCO_to_RCOPeqOOO', 'obvious', 'bioisostere',
     '[*:1]CO',
     '[*:1]COP(=O)(O)O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=4
    ('mmp0051_Rc1cccClcc1_to_Rc1cccOCcc1', 'subtle', 'bioisostere',
     '[*:1]c1ccc(Cl)cc1',
     '[*:1]c1ccc(OC)cc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0052_RNCC_to_RNCCCC', 'moderate', 'homologation',
     '[*:1]N(C)C',
     '[*:1]N(CC)CC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=2
    ('mmp0053_RNCC_to_RN1CCCCC1', 'moderate', 'scaffold-hop',
     '[*:1]N(C)C',
     '[*:1]N1CCCCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=3
    ('mmp0054_RCCCNCCCC_to_RCCCNCCO', 'subtle', 'bioisostere',
     '[*:1]CCCN(CC)CC',
     '[*:1]CCCNCCO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-1
    ('mmp0055_Rc1cccOcc1_to_Rc1cccOCcc1', 'subtle', 'homologation',
     '[*:1]c1ccc(O)cc1',
     '[*:1]c1ccc(OC)cc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0056_RC1CC2CeqCC1C2_to_RC1CCCCC1', 'subtle', 'scaffold-hop',
     '[*:1]C1CC2C=CC1C2',
     '[*:1]C1CCCCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-1
    ('mmp0057_RC1CC2CeqCC1C2_to_RC1CCCC1', 'moderate', 'scaffold-hop',
     '[*:1]C1CC2C=CC1C2',
     '[*:1]C1CCCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-2
    ('mmp0058_RC_to_RCO', 'subtle', 'bioisostere',
     '[*:1]C',
     '[*:1]CO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0059_Rc1ccccc1_to_Rc1ccccc1C', 'subtle', 'homologation',
     '[*:1]c1ccccc1',
     '[*:1]c1ccccc1C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0060_RCC_to_Rc1ccccc1', 'obvious', 'scaffold-hop',
     '[*:1]CC',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=4
    ('mmp0061_ROC1CCNCCC1_to_ROCCNCC', 'moderate', 'scaffold-hop',
     '[*:1]OC1CCN(C)CC1',
     '[*:1]OCCN(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-2
    ('mmp0062_RCCCNCCCC_to_ROCCNCC', 'moderate', 'bioisostere',
     '[*:1]CC(C)NC(C)(C)C',
     '[*:1]OCCN(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-2
    ('mmp0063_RCCCNCCCC_to_ROC1CCNCCC1', 'subtle', 'scaffold-hop',
     '[*:1]CC(C)NC(C)(C)C',
     '[*:1]OC1CCN(C)CC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=0
    ('mmp0064_RC_to_ROC', 'subtle', 'bioisostere',
     '[*:1]C',
     '[*:1]OC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0065_Rc1ccccc1_to_Rc1ccccc1F', 'subtle', 'halogen-walk',
     '[*:1]c1ccccc1',
     '[*:1]c1ccccc1F',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0066_RCCCC_to_RCCC', 'subtle', 'homologation',
     '[*:1]C(C)(C)C',
     '[*:1]C(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-1
    ('mmp0067_RNCCCC_to_RNCCO', 'subtle', 'bioisostere',
     '[*:1]N(CC)CC',
     '[*:1]NCCO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-1
    ('mmp0068_RNCc1ccccn1_to_Rc1cccCCcn1', 'subtle', 'other',
     '[*:1]N(C)c1ccccn1',
     '[*:1]c1ccc(CC)cn1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=0
    ('mmp0069_RCl_to_ROPeqOOO', 'obvious', 'bioisostere',
     '[*:1]Cl',
     '[*:1]OP(=O)(O)O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=4
    ('mmp0070_RCeqCCtriCCCCC_to_RCeqCc1ccccc1', 'subtle', 'scaffold-hop',
     '[*:1]/C=C\\C#CC(C)(C)C',
     '[*:1]/C=C\\c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=0
    ('mmp0071_Rc1cccOCcc1_to_Rc1cccs1', 'moderate', 'bioisostere',
     '[*:1]c1ccc(OC)cc1',
     '[*:1]c1cccs1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-3
    ('mmp0072_RCtriCCNCCCC_to_RC1eqNCCCN1C', 'subtle', 'scaffold-hop',
     '[*:1]C#CCN(CC)CC',
     '[*:1]C1=NCCCN1C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-1
    ('mmp0073_Rc1ccccn1_to_Rc1nccs1', 'subtle', 'bioisostere',
     '[*:1]c1ccccn1',
     '[*:1]c1nccs1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-1
    ('mmp0074_RC_to_RCCNCCCC', 'obvious', 'bioisostere',
     '[*:1]C',
     '[*:1]CCN(CC)CC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=6
    ('mmp0075_RCC1CC1_to_RCCCC', 'subtle', 'scaffold-hop',
     '[*:1]CC1CC1',
     '[*:1]CCCC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=0
    ('mmp0076_RCCC_to_RCCCC', 'subtle', 'homologation',
     '[*:1]CCC',
     '[*:1]CCCC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0077_RC_to_RCc1ccccCc1', 'obvious', 'scaffold-hop',
     '[*:1]C',
     '[*:1]Cc1cccc(C)c1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=7
    ('mmp0078_RC_to_RCCOCCeqOO', 'obvious', 'bioisostere',
     '[*:1]C',
     '[*:1]CCOCC(=O)O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=6
    ('mmp0079_RCCOCCO_to_RCc1ccccCc1', 'moderate', 'scaffold-hop',
     '[*:1]CCOCCO',
     '[*:1]Cc1cccc(C)c1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=2
    ('mmp0080_RCCOCCeqOO_to_RCc1ccccCc1', 'subtle', 'scaffold-hop',
     '[*:1]CCOCC(=O)O',
     '[*:1]Cc1cccc(C)c1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0081_RCCCCNCC_to_RCCCNC', 'moderate', 'homologation',
     '[*:1]CC(C)CN(C)C',
     '[*:1]CCCNC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-2
    ('mmp0082_RCHCCO_to_RCHCCCO', 'subtle', 'homologation',
     '[*:1][C@@H](C)CO',
     '[*:1][C@@H](CC)CO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0083_RC1CC1_to_RCC', 'subtle', 'scaffold-hop',
     '[*:1]C1CC1',
     '[*:1]CC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-1
    ('mmp0084_RCeqONCHCCO_to_RCeqONCHCCCO', 'subtle', 'homologation',
     '[*:1]C(=O)N[C@@H](C)CO',
     '[*:1]C(=O)N[C@@H](CC)CO',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0085_ROC_to_RSC', 'subtle', 'bioisostere',
     '[*:1]OC',
     '[*:1]SC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=0
    ('mmp0086_RCeqNO_to_RCeqNO', 'subtle', 'other',
     '[*:1]/C=N/O',
     '[*:1]/C=N\\O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=0
    ('mmp0087_RCCeqO_to_RCFFF', 'subtle', 'bioisostere',
     '[*:1]C(C)=O',
     '[*:1]C(F)(F)F',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=1
    ('mmp0088_RCFFF_to_RSCC', 'subtle', 'bioisostere',
     '[*:1]C(F)(F)F',
     '[*:1]SCC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=-1
    ('mmp0089_RCl_to_RSCC', 'moderate', 'bioisostere',
     '[*:1]Cl',
     '[*:1]SCC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=2
    ('mmp0090_RCCCl_to_RCCOPeqOOO', 'obvious', 'bioisostere',
     '[*:1]CCCl',
     '[*:1]CCOP(=O)(O)O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=4 pairs, Δheavy=4
    ('mmp0091_Rc1ccccOc1_to_Rc1ccccc1', 'subtle', 'bioisostere',
     '[*:1]c1cccc(O)c1',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=-1
    ('mmp0092_Rc1cccClcc1_to_Rc1cccFcc1', 'subtle', 'halogen-walk',
     '[*:1]c1ccc(Cl)cc1',
     '[*:1]c1ccc(F)cc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=0
    ('mmp0093_RCc1ccccc1_to_RCHNc1ccccc1', 'subtle', 'bioisostere',
     '[*:1]Cc1ccccc1',
     '[*:1][C@H](N)c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0094_RCO_to_RCOCCeqO', 'moderate', 'homologation',
     '[*:1]CO',
     '[*:1]COC(C)=O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=3
    ('mmp0095_Rc1cccFcc1_to_Rc1ccccc1', 'subtle', 'halogen-walk',
     '[*:1]c1ccc(F)cc1',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=-1
    ('mmp0096_RCC_to_RCCC', 'subtle', 'homologation',
     '[*:1]CC',
     '[*:1]CCC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0097_RC_to_RO', 'subtle', 'bioisostere',
     '[*:1]C',
     '[*:1]O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=0
    ('mmp0098_RCCCC_to_Rc1ccccc1', 'moderate', 'scaffold-hop',
     '[*:1]CC(C)C',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=2
    ('mmp0099_RCC_to_RCCeqC', 'subtle', 'homologation',
     '[*:1]CC',
     '[*:1]CC=C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0100_RC1eqCCCCC1_to_Rc1ccccc1', 'subtle', 'scaffold-hop',
     '[*:1]C1=CCCCC1',
     '[*:1]c1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=0
    ('mmp0101_RCCCCC_to_RCCCC', 'subtle', 'homologation',
     '[*:1]C(C)CCC',
     '[*:1]CC(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=-1
    ('mmp0102_RC_to_RCOCCeqO', 'obvious', 'bioisostere',
     '[*:1]C',
     '[*:1]COC(C)=O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=4
    ('mmp0103_Rc1ccccc1Cl_to_Rc1ccccc1F', 'subtle', 'halogen-walk',
     '[*:1]c1ccccc1Cl',
     '[*:1]c1ccccc1F',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=0
    ('mmp0104_RNCCCC_to_RN1CCNCCC1', 'moderate', 'scaffold-hop',
     '[*:1]N(CC)CC',
     '[*:1]N1CCN(C)CC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=2
    ('mmp0105_RCCCO_to_RCCC', 'subtle', 'bioisostere',
     '[*:1]C(C)(C)O',
     '[*:1]C(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=-1
    ('mmp0106_RNCCCC_to_RN1CCCCC1', 'subtle', 'scaffold-hop',
     '[*:1]N(CC)CC',
     '[*:1]N1CCCCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0107_RCNeqNO_to_RC1eqNCCN1', 'subtle', 'scaffold-hop',
     '[*:1]/C(N)=N/O',
     '[*:1]C1=NCCN1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0108_RC1CC1_to_RC1CCC1', 'subtle', 'homologation',
     '[*:1]C1CC1',
     '[*:1]C1CCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0109_RC1CC1_to_Rc1cccFcc1', 'obvious', 'scaffold-hop',
     '[*:1]C1CC1',
     '[*:1]c1ccc(F)cc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=4
    ('mmp0110_RC1CC1_to_RCeqC', 'subtle', 'scaffold-hop',
     '[*:1]C1CC1',
     '[*:1]C=C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=-1
    ('mmp0111_RCeqC_to_RCeqCCC', 'moderate', 'homologation',
     '[*:1]C=C',
     '[*:1]C=C(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=2
    ('mmp0112_Rc1ccccn1_to_Rc1ncccn1', 'subtle', 'other',
     '[*:1]c1ccccn1',
     '[*:1]c1ncccn1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=0
    ('mmp0113_RC_to_RCCCC', 'moderate', 'homologation',
     '[*:1]C',
     '[*:1]CC(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=3
    ('mmp0114_RCC1eqNCCN1_to_RCCN1CCCC1', 'subtle', 'homologation',
     '[*:1]CC1=NCCN1',
     '[*:1]CCN1CCCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0115_RCCNeqNO_to_RCC1eqNCCN1', 'subtle', 'scaffold-hop',
     '[*:1]C/C(N)=N/O',
     '[*:1]CC1=NCCN1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0116_RC1CCNCCC1_to_RCC1eqNCCN1', 'subtle', 'homologation',
     '[*:1]C1CCN(C)CC1',
     '[*:1]CC1=NCCN1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=-1
    ('mmp0117_RC_to_RCCc1ccccc1', 'obvious', 'scaffold-hop',
     '[*:1]C',
     '[*:1]CCc1ccccc1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=7
    ('mmp0118_RCC1CC1_to_RCC1CCC1', 'subtle', 'homologation',
     '[*:1]CC1CC1',
     '[*:1]CC1CCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0119_RCCeqC_to_RCCOC', 'subtle', 'bioisostere',
     '[*:1]CC=C',
     '[*:1]CCOC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0120_RC_to_RCCOC', 'moderate', 'bioisostere',
     '[*:1]C',
     '[*:1]CCOC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=3
    ('mmp0121_RCC1CC1_to_RCCeqC', 'subtle', 'scaffold-hop',
     '[*:1]CC1CC1',
     '[*:1]CC=C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=-1
    ('mmp0122_RCCeqC_to_RCCeqCCC', 'moderate', 'homologation',
     '[*:1]CC=C',
     '[*:1]CC=C(C)C',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=2
    ('mmp0123_RCCNCCCC_to_RCCN1CCCCC1', 'subtle', 'scaffold-hop',
     '[*:1]CCN(CC)CC',
     '[*:1]CCN1CCCCC1',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=1
    ('mmp0124_RCCC_to_RCC', 'subtle', 'homologation',
     '[*:1]C(C)C',
     '[*:1]CC',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=-1
    ('mmp0125_Rn1cccNnc1eqO_to_Rn1cncNnc1eqO', 'subtle', 'other',
     '[*:1]n1ccc(N)nc1=O',
     '[*:1]n1cnc(N)nc1=O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=0
    ('mmp0126_RCeqOCO_to_RCeqOCOCCeqO', 'moderate', 'homologation',
     '[*:1]C(=O)CO',
     '[*:1]C(=O)COC(C)=O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=3
    ('mmp0127_RC_to_RF', 'subtle', 'halogen-walk',
     '[*:1]C',
     '[*:1]F',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=0
    ('mmp0128_RCCCeqOO_to_RCHCCeqOO', 'subtle', 'other',
     '[*:1]C(C)C(=O)O',
     '[*:1][C@H](C)C(=O)O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=0
    ('mmp0129_RCeqOCC_to_RCCeqO', 'subtle', 'homologation',
     '[*:1]C(=O)CC',
     '[*:1]C(C)=O',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=-1
    ('mmp0130_RCCeqO_to_RCl', 'moderate', 'bioisostere',
     '[*:1]C(C)=O',
     '[*:1]Cl',
     'mmpdb-mined(authentic@intelligent_pharma_50k_v2.pt)'),  # support=3 pairs, Δheavy=-2
]

# Support counts (matched pairs) per rule, for weighting:
SUPPORT = {
    'mmp0000_RC_to_RCC': 31,
    'mmp0001_RCFFF_to_RCl': 17,
    'mmp0002_Rc1cccClcc1_to_Rc1ccccc1': 14,
    'mmp0003_RO_to_ROPeqOOO': 13,
    'mmp0004_RC1CCCCC1_to_Rc1ccccc1': 13,
    'mmp0005_Rc1ccccc1_to_Rc1cccs1': 12,
    'mmp0006_RC1CCCC1_to_RC1CCCCC1': 11,
    'mmp0007_RC_to_RCl': 11,
    'mmp0008_RC_to_RCC1CC1': 11,
    'mmp0009_RO_to_ROC': 11,
    'mmp0010_RC_to_RCCCC': 10,
    'mmp0011_Rc1cccBrcc1_to_Rc1cccClcc1': 9,
    'mmp0012_Rc1ccccc1_to_Rc1ccccc1Cl': 9,
    'mmp0013_RNCC_to_RNC': 9,
    'mmp0014_RCC_to_RCCO': 9,
    'mmp0015_RC_to_RCCO': 9,
    'mmp0016_RBr_to_RCl': 9,
    'mmp0017_RC1CCCC1_to_Rc1ccccc1': 8,
    'mmp0018_RO_to_ROCCeqO': 8,
    'mmp0019_RC_to_RCCeqC': 8,
    'mmp0020_RNCCCC_to_RNCCCCO': 8,
    'mmp0021_RNCC_to_RN1CCNCCC1': 8,
    'mmp0022_RCl_to_RF': 8,
    'mmp0023_Rc1cccOcc1_to_Rc1ccccc1': 7,
    'mmp0024_Rc1cccBrcc1_to_Rc1ccccc1': 7,
    'mmp0025_RN1CCCC1_to_RN1CCCCC1': 7,
    'mmp0026_RC_to_RCCOCCO': 7,
    'mmp0027_RCc1ccccc1_to_RCc1cccs1': 6,
    'mmp0028_RC_to_RCCC': 6,
    'mmp0029_Rc1cccClcc1_to_Rc1cccClcc1Cl': 6,
    'mmp0030_RC1CCCC1_to_Rc1cccs1': 6,
    'mmp0031_RC1CCCCC1_to_Rc1cccs1': 6,
    'mmp0032_Rc1ccccc1_to_Rc1ccccn1': 6,
    'mmp0033_RCCNCC_to_ROCCNCC': 6,
    'mmp0034_RCl_to_RO': 6,
    'mmp0035_RCCCNCC_to_RCCCNC': 6,
    'mmp0036_RCCCCNCC_to_RCCCNCC': 6,
    'mmp0037_RC_to_RCCC': 6,
    'mmp0038_RCCCl_to_RCCO': 6,
    'mmp0039_RCCO_to_RCCOPeqOOO': 6,
    'mmp0040_Rc1cccOCcc1_to_Rc1ccccc1': 5,
    'mmp0041_RCCN1CCCC1_to_RCCN1CCCCC1': 5,
    'mmp0042_ROCCeqOO_to_ROCCO': 5,
    'mmp0043_RC1CCNCCC1_to_RCCNCC': 5,
    'mmp0044_RCCOCCeqOO_to_RCCOCCO': 5,
    'mmp0045_RCCeqOO_to_RCCO': 5,
    'mmp0046_RCl_to_ROC': 5,
    'mmp0047_RCCO_to_RCC': 5,
    'mmp0048_RCtriCCCCC_to_Rc1ccccc1': 4,
    'mmp0049_RC1CCCO1_to_Rc1ccco1': 4,
    'mmp0050_RCO_to_RCOPeqOOO': 4,
    'mmp0051_Rc1cccClcc1_to_Rc1cccOCcc1': 4,
    'mmp0052_RNCC_to_RNCCCC': 4,
    'mmp0053_RNCC_to_RN1CCCCC1': 4,
    'mmp0054_RCCCNCCCC_to_RCCCNCCO': 4,
    'mmp0055_Rc1cccOcc1_to_Rc1cccOCcc1': 4,
    'mmp0056_RC1CC2CeqCC1C2_to_RC1CCCCC1': 4,
    'mmp0057_RC1CC2CeqCC1C2_to_RC1CCCC1': 4,
    'mmp0058_RC_to_RCO': 4,
    'mmp0059_Rc1ccccc1_to_Rc1ccccc1C': 4,
    'mmp0060_RCC_to_Rc1ccccc1': 4,
    'mmp0061_ROC1CCNCCC1_to_ROCCNCC': 4,
    'mmp0062_RCCCNCCCC_to_ROCCNCC': 4,
    'mmp0063_RCCCNCCCC_to_ROC1CCNCCC1': 4,
    'mmp0064_RC_to_ROC': 4,
    'mmp0065_Rc1ccccc1_to_Rc1ccccc1F': 4,
    'mmp0066_RCCCC_to_RCCC': 4,
    'mmp0067_RNCCCC_to_RNCCO': 4,
    'mmp0068_RNCc1ccccn1_to_Rc1cccCCcn1': 4,
    'mmp0069_RCl_to_ROPeqOOO': 4,
    'mmp0070_RCeqCCtriCCCCC_to_RCeqCc1ccccc1': 4,
    'mmp0071_Rc1cccOCcc1_to_Rc1cccs1': 4,
    'mmp0072_RCtriCCNCCCC_to_RC1eqNCCCN1C': 4,
    'mmp0073_Rc1ccccn1_to_Rc1nccs1': 4,
    'mmp0074_RC_to_RCCNCCCC': 4,
    'mmp0075_RCC1CC1_to_RCCCC': 4,
    'mmp0076_RCCC_to_RCCCC': 4,
    'mmp0077_RC_to_RCc1ccccCc1': 4,
    'mmp0078_RC_to_RCCOCCeqOO': 4,
    'mmp0079_RCCOCCO_to_RCc1ccccCc1': 4,
    'mmp0080_RCCOCCeqOO_to_RCc1ccccCc1': 4,
    'mmp0081_RCCCCNCC_to_RCCCNC': 4,
    'mmp0082_RCHCCO_to_RCHCCCO': 4,
    'mmp0083_RC1CC1_to_RCC': 4,
    'mmp0084_RCeqONCHCCO_to_RCeqONCHCCCO': 4,
    'mmp0085_ROC_to_RSC': 4,
    'mmp0086_RCeqNO_to_RCeqNO': 4,
    'mmp0087_RCCeqO_to_RCFFF': 4,
    'mmp0088_RCFFF_to_RSCC': 4,
    'mmp0089_RCl_to_RSCC': 4,
    'mmp0090_RCCCl_to_RCCOPeqOOO': 4,
    'mmp0091_Rc1ccccOc1_to_Rc1ccccc1': 3,
    'mmp0092_Rc1cccClcc1_to_Rc1cccFcc1': 3,
    'mmp0093_RCc1ccccc1_to_RCHNc1ccccc1': 3,
    'mmp0094_RCO_to_RCOCCeqO': 3,
    'mmp0095_Rc1cccFcc1_to_Rc1ccccc1': 3,
    'mmp0096_RCC_to_RCCC': 3,
    'mmp0097_RC_to_RO': 3,
    'mmp0098_RCCCC_to_Rc1ccccc1': 3,
    'mmp0099_RCC_to_RCCeqC': 3,
    'mmp0100_RC1eqCCCCC1_to_Rc1ccccc1': 3,
    'mmp0101_RCCCCC_to_RCCCC': 3,
    'mmp0102_RC_to_RCOCCeqO': 3,
    'mmp0103_Rc1ccccc1Cl_to_Rc1ccccc1F': 3,
    'mmp0104_RNCCCC_to_RN1CCNCCC1': 3,
    'mmp0105_RCCCO_to_RCCC': 3,
    'mmp0106_RNCCCC_to_RN1CCCCC1': 3,
    'mmp0107_RCNeqNO_to_RC1eqNCCN1': 3,
    'mmp0108_RC1CC1_to_RC1CCC1': 3,
    'mmp0109_RC1CC1_to_Rc1cccFcc1': 3,
    'mmp0110_RC1CC1_to_RCeqC': 3,
    'mmp0111_RCeqC_to_RCeqCCC': 3,
    'mmp0112_Rc1ccccn1_to_Rc1ncccn1': 3,
    'mmp0113_RC_to_RCCCC': 3,
    'mmp0114_RCC1eqNCCN1_to_RCCN1CCCC1': 3,
    'mmp0115_RCCNeqNO_to_RCC1eqNCCN1': 3,
    'mmp0116_RC1CCNCCC1_to_RCC1eqNCCN1': 3,
    'mmp0117_RC_to_RCCc1ccccc1': 3,
    'mmp0118_RCC1CC1_to_RCC1CCC1': 3,
    'mmp0119_RCCeqC_to_RCCOC': 3,
    'mmp0120_RC_to_RCCOC': 3,
    'mmp0121_RCC1CC1_to_RCCeqC': 3,
    'mmp0122_RCCeqC_to_RCCeqCCC': 3,
    'mmp0123_RCCNCCCC_to_RCCN1CCCCC1': 3,
    'mmp0124_RCCC_to_RCC': 3,
    'mmp0125_Rn1cccNnc1eqO_to_Rn1cncNnc1eqO': 3,
    'mmp0126_RCeqOCO_to_RCeqOCOCCeqO': 3,
    'mmp0127_RC_to_RF': 3,
    'mmp0128_RCCCeqOO_to_RCHCCeqOO': 3,
    'mmp0129_RCeqOCC_to_RCCeqO': 3,
    'mmp0130_RCCeqO_to_RCl': 3,
}
